package tintor.netrek.common;

public enum ShipClass {
	Scout, Destroyer, Cruiser, Battleship, Assault, Starbase;

	public String name;
	public char key;

	public int phaserdamage;
	public int phaserfuse;
	public int phasercost;

	public int torpdamage;
	public int torpspeed;
	public int torpfuse;
	public int torpturns;
	public int torpcost;

	public int plasmaspeed;
	public int plasmafuse;
	public int plasmaturns;
	public int plasmacost;
	public int plasmadamage = -1;

	public int detcost = 100;
	public int warpcost;
	public int cloakcost;
	public int shieldcost;

	public int turns;
	public int accs = 100;
	public int accint;
	public int decint;
	public int repair;
	public int recharge;
	public int egncoolrate;
	public int wpncoolrate;
	public int mass;
	public int tractstrength;
	public float tractrange;

	public int maxarmies;
	public int maxfuel;
	public int maxspeed;
	public int maxshield;
	public int maxdamage;
	public int maxegntemp;
	public int maxwpntemp;

	static {
		Scout.name = "SC";
		Scout.turns = 570000;
		Scout.accint = 200;
		Scout.decint = 270;
		Scout.torpdamage = 25;
		Scout.phaserfuse = 10;
		Scout.phaserdamage = 75;
		Scout.torpspeed = 16;
		Scout.torpfuse = 16;
		Scout.maxspeed = 12;
		Scout.repair = 80;
		Scout.maxfuel = 5000;
		Scout.torpcost = 7 * Scout.torpdamage;
		Scout.phasercost = 7 * Scout.phaserdamage;
		Scout.warpcost = 2;
		Scout.cloakcost = 17;
		Scout.shieldcost = 2;
		Scout.recharge = 8;
		Scout.maxarmies = 2;
		Scout.maxshield = 75;
		Scout.maxdamage = 75;
		Scout.wpncoolrate = 3;
		Scout.egncoolrate = 8;
		Scout.maxwpntemp = 1000;
		Scout.maxegntemp = 1000;
		Scout.mass = 1500;
		Scout.tractstrength = 2000;
		Scout.tractrange = .7f;

		Destroyer.name = "DD";
		Destroyer.key = 'D';
		Destroyer.turns = 310000;
		Destroyer.accint = 200;
		Destroyer.decint = 300;
		Destroyer.torpdamage = 30;
		Destroyer.plasmadamage = 75;
		Destroyer.phaserfuse = 10;
		Destroyer.phaserdamage = 85;
		Destroyer.torpspeed = 14;
		Destroyer.torpfuse = 30;
		Destroyer.plasmaspeed = 15;
		Destroyer.plasmafuse = 30;
		Destroyer.plasmaturns = 1;
		Destroyer.maxspeed = 10;
		Destroyer.repair = 100;
		Destroyer.maxfuel = 7000;
		Destroyer.torpcost = 7 * Destroyer.torpdamage;
		Destroyer.plasmacost = 30 * Destroyer.plasmadamage;
		Destroyer.phasercost = 7 * Destroyer.phaserdamage;
		Destroyer.warpcost = 3;
		Destroyer.cloakcost = 21;
		Destroyer.shieldcost = 3;
		Destroyer.recharge = 11;
		Destroyer.maxarmies = 5;
		Destroyer.maxshield = 85;
		Destroyer.maxdamage = 85;
		Destroyer.wpncoolrate = 2;
		Destroyer.egncoolrate = 7;
		Destroyer.maxwpntemp = 1000;
		Destroyer.maxegntemp = 1000;
		Destroyer.mass = 1800;
		Destroyer.tractstrength = 2500;
		Destroyer.tractrange = .9f;

		Cruiser.name = "CA";
		Cruiser.key = 'C';
		Cruiser.turns = 170000;
		Cruiser.accint = 150;
		Cruiser.decint = 200;
		Cruiser.torpdamage = 40;
		Cruiser.plasmadamage = 100;
		Cruiser.phaserfuse = 10;
		Cruiser.phaserdamage = 100;
		Cruiser.torpspeed = 12;
		Cruiser.torpfuse = 40;
		Cruiser.plasmaspeed = 15;
		Cruiser.plasmafuse = 35;
		Cruiser.plasmaturns = 1;
		Cruiser.maxspeed = 9;
		Cruiser.repair = 110;
		Cruiser.maxfuel = 10000;
		Cruiser.torpcost = 7 * Cruiser.torpdamage;
		Cruiser.plasmacost = 30 * Cruiser.plasmadamage;
		Cruiser.phasercost = 7 * Cruiser.phaserdamage;
		Cruiser.warpcost = 4;
		Cruiser.cloakcost = 26;
		Cruiser.shieldcost = 3;
		Cruiser.recharge = 12;
		Cruiser.maxarmies = 10;
		Cruiser.maxshield = 100;
		Cruiser.maxdamage = 100;
		Cruiser.wpncoolrate = 2;
		Cruiser.egncoolrate = 6;
		Cruiser.maxwpntemp = 1000;
		Cruiser.maxegntemp = 1000;
		Cruiser.mass = 2000;
		Cruiser.tractstrength = 3000;
		Cruiser.tractrange = 1.0f;

		Battleship.name = "BB";
		Battleship.key = 'B';
		Battleship.turns = 75000;
		Battleship.accint = 80;
		Battleship.decint = 180;
		Battleship.torpdamage = 40;
		Battleship.plasmadamage = 130;
		Battleship.phaserfuse = 10;
		Battleship.phaserdamage = 105;
		Battleship.torpspeed = 12;
		Battleship.torpfuse = 40;
		Battleship.plasmaspeed = 15;
		Battleship.plasmafuse = 35;
		Battleship.plasmaturns = 1;
		Battleship.maxspeed = 8;
		Battleship.repair = 125;
		Battleship.maxfuel = 14000;
		Battleship.torpcost = 9 * Battleship.torpdamage;
		Battleship.plasmacost = 30 * Battleship.plasmadamage;
		Battleship.phasercost = 10 * Battleship.phaserdamage;
		Battleship.warpcost = 6;
		Battleship.cloakcost = 30;
		Battleship.shieldcost = 3;
		Battleship.recharge = 14;
		Battleship.maxarmies = 6;
		Battleship.maxshield = 130;
		Battleship.maxdamage = 130;
		Battleship.wpncoolrate = 3;
		Battleship.egncoolrate = 6;
		Battleship.maxwpntemp = 1000;
		Battleship.maxegntemp = 1000;
		Battleship.mass = 2300;
		Battleship.tractstrength = 3700;
		Battleship.tractrange = 1.2f;

		Assault.name = "AS";
		Assault.key = 'A';
		Assault.turns = 120000;
		Assault.accint = 100;
		Assault.decint = 200;
		Assault.torpdamage = 30;
		Assault.phaserfuse = 10;
		Assault.phaserdamage = 80;
		Assault.torpspeed = 16;
		Assault.torpfuse = 30;
		Assault.maxspeed = 8;
		Assault.repair = 120;
		Assault.maxfuel = 6000;
		Assault.torpcost = 9 * Assault.torpdamage;
		Assault.phasercost = 7 * Assault.phaserdamage;
		Assault.warpcost = 3;
		Assault.cloakcost = 17;
		Assault.shieldcost = 3;
		Assault.recharge = 10;
		Assault.maxarmies = 20;
		Assault.maxshield = 80;
		Assault.maxdamage = 200;
		Assault.wpncoolrate = 2;
		Assault.egncoolrate = 6;
		Assault.maxwpntemp = 1000;
		Assault.maxegntemp = 1200;
		Assault.mass = 2300;
		Assault.tractstrength = 2500;
		Assault.tractrange = .7f;

		Starbase.name = "SB";
		Starbase.key = 'O';
		Starbase.turns = 50000;
		Starbase.accint = 100;
		Starbase.decint = 200;
		Starbase.torpdamage = 30;
		Starbase.plasmadamage = 150;
		Starbase.phaserfuse = 4;
		Starbase.phaserdamage = 120;
		Starbase.torpspeed = 14;
		Starbase.torpfuse = 30;
		Starbase.plasmaspeed = 15;
		Starbase.plasmafuse = 25;
		Starbase.plasmaturns = 1;
		Starbase.repair = 140;
		Starbase.maxfuel = 60000;
		Starbase.torpcost = 10 * Starbase.torpdamage;
		Starbase.plasmacost = 25 * Starbase.plasmadamage;
		Starbase.phasercost = 8 * Starbase.phaserdamage;
		Starbase.warpcost = 10;
		Starbase.cloakcost = 75;
		Starbase.shieldcost = 6;
		Starbase.recharge = 35;
		Starbase.maxarmies = 25;
		Starbase.maxshield = 500;
		Starbase.maxdamage = 600;
		Starbase.wpncoolrate = 4;
		Starbase.egncoolrate = 4;
		Starbase.maxspeed = 2;
		Starbase.maxwpntemp = 1300;
		Starbase.maxegntemp = 1000;
		Starbase.mass = 5000;
		Starbase.tractstrength = 8000;
		Starbase.tractrange = 1.5f;
	}
}